### PR TITLE
[FEATURE] Add isInteger code snippets

### PR DESCRIPTION
**Pull request by peter279k**
## Description
- Add `isInteger` code snippets.

## PR Type
- [X] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)

## Guidelines
- [X] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by peter279k** [comment]
The `isNumber` just checks the value is numeric.

To check the numeric values, I think we should implement the `isInteger` or `isFloat`.

And it can check the numeric values are float or integer numbers in advanced.

**Comment by Chalarangelo** [comment]
We used to have both of those and we dropped them for whatever reason. There were a bunch of issues with the way JS parses numbers and many other things as far as I remember. `isNumber` was the most viable option, anything more complicated than that is bound to require some checks that are not 30-seconds long or intuitive enough. (You can check old discussions about this in some of the older issues)

**Comment by peter279k** [comment]
@Chalarangelo, thank you for your explanation.

The advanced numeric value check will be complicated and it's not part of the `30-seconds-code`.

**Comment by skatcat31** [comment]
notes:
It's probably best to avoid doing any sort of advanced logic on basics since they're still instance. You never actually have access to a "basic" value in JS. `1` is actually an instance of Number with a primitive value flag. In JS you can't touch the Primitives from user space, and thus they can always be coerced. Checking `isInteger` or along those lines is "worthless" because at next tick it could be a float and it will still behave exactly the same mathematically to user space. It is better to instead force the coercion without modifying the pointer value if you need an integer, or to throw if it's not exactly modulo by 1 since for all intents and purposes `1.0 === 1`

```js
1%1 // 0
X%1 === 0 // is an integer
Y%1 !== 0 // is a float
1.0 === 1 // true
```

**Pull request closed without merging**
