### PR TITLE
[FIX] Improve the readability of tomorrow.js (solves #775)

### PR DESCRIPTION
**Pull request by filipdanic**
As discussed in #775, `tomorrow.js` is hard to read. I’ve updated the implementation to simplify things.

I’ve removed the boolean parameter `long`. It’s a code smell and only adds to the complexity of the function. We should encourage folks to use a different method to add a prefix/suffix to a string. 

## PR Type
- [✅ ] Snippets, Tests & Tags (new snippets, **updated snippets**, re-tagging of snippets, added/updated tests)

## Guidelines
- [✅] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by skatcat31** [comment]
will `Date#toISOString()` cause any issues with it being UTC versus local like `Date#getFullYear` etc?

**Comment by filipdanic** [comment]
Good point – it probably fails on New Year's Eve.

But I’m thinking that replacing `new Date()` with `new Date(Date.now())` should solve that issue?

**Comment by Chalarangelo** [comment]
I'm putting this on hold for a little bit, until we figure it out. Note that the test structure for the snippet needs to be updated to the new format, but that can be done right before the merge from a maintainer, as well.

**Comment by Chalarangelo** [comment]
Based on [this answer on SO](https://stackoverflow.com/a/23081260/1650200) and after some trial and error, I came up with this solution to the issue ([repl here](https://repl.it/repls/EnchantedInsecureIntegers)):
```js
const tomorrow = () => {
  let date = new Date();
  date.setDate(date.getDate() + 1);
  return date;
}
```

In the same repl, I describe a proposal for a `nextDate()` function and showcase some tests. These could solve the problem one and for all, right?

@skatcat31 Any thoughts?

**Comment by skatcat31** [comment]
Also did we ever decide if we were going to use `Class#prototypeMethod()` notation?

**Comment by RobertAKARobin** [comment]
Out of curiosity, how did this make it into `master` with a failing test?

**Comment by Chalarangelo** [comment]
@RobertAKARobin this is one of our oldest snippets, somehow it worked for a while, then it broke at some point. It's probably one of the most problematic snippets in the entire codebase so far.

**Comment by skatcat31** [comment]
To be fair @RobertAKARobin we've considered voting on removing it. It's a problem and with the recent possible changes to DST in PT it might get even more confusing.

**Pull request merged**
