### PR TITLE
Easy slug snippet

### PR DESCRIPTION
**Pull request by Creatoon**
Created a snippet that can create a URL friendly slug without the use of any regex, and will be easy to learn for newbies of javascript.

### CODE REVIEW

**Review by Trinityyi — COMMENTED** [review]
Thanks for contributing. However this is a duplicate of an existing snippet - [slugify](https://www.30secondsofcode.org/js/s/slugify).

**Comment by Creatoon** [comment]
@Trinityyi mam , it's not that similar code,  I reviewed that code and that was converting the string to slug using regular expression.

But if you look at my code it is not using any regular expression,  I wrote this snippet for those people who don't understand regular expressions.

Please review the code again mam

**Review by Tinokura — COMMENTED** [review]
Hahahaha

**Comment by Creatoon** [comment]
@Tinokura What happened sir,  is there any mistake?

**Comment by Chalarangelo** [comment]
@Creatoon Implementation details are irrelevant. We only keep one snippet for each piece of functionality.

**Pull request closed without merging**
