### PR TITLE
[FEATURE] Sum of squares of numbers

### PR DESCRIPTION
**Pull request by saqib053**
## PR Type
- [ ] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [ ] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
- [ ] My PR doesn't include any `testlog` changes.

### CODE REVIEW

**Comment by flxwu** [comment]
We added a PR template for a reason, please use it. Also discard all the changes that don't have anything to do with your snippet, i.e. the files without changes aswell as testlog and the package lockfile.

**Comment by flxwu** [comment]
tbh I vote for closing this PR for now. People should open their PR properly and not just for the sake of it. also I don't see a major advantage in the snippet as I've personally never used this, and even if it's easy enough to write yourself or not

**Comment by saqib053** [comment]
I can try to fix up the things. Just give me a bit of time.

**Comment by Chalarangelo** [comment]
@saqib053 To avoid having a ton of useless commits, please submit a new PR under archive so we can properly review it. I doubt this is a very useful snippet, but you can still PR it nonetheless. Closing for now...

**Comment by saqib053** [comment]
very rude behaviour

**Comment by flxwu** [comment]
sorry, we really don't want to discourage you. But projects as big as this need contributors that align with the contributor guidelines, so that both you as a contributor can get your PR quickly merged and we as maintainers spend less time on reviews. Also, if you care about this project and your contribution, you would likely add a description and read the guidelines.

**Comment by saqib053** [comment]
You guys are absolutely right in your own domain. I have read the guidelines and tried to follow those. This is my first every contribution to any public project. I knew there will be mistakes but was not expecting such harsh comments. Nevertheless I wanted to contribute for the sake of helping people and writing some useful code. I will try again with better PR.

**Comment by saqib053** [comment]
@Chalarangelo how I can create a PR in under archive?

**Comment by flxwu** [comment]
Just create your snippet in the `snippet_archive` folder 🙂

**Comment by Chalarangelo** [comment]
@saqib053 you should just put your snippet in the `snippet_archive` folder.

**Comment by Chalarangelo** [comment]
@saqib053 As a general rule of thumb, you should know that a lot of PRs in open-source projects get rejected often. This is a very common situation and shouldn't discourage you from contributing, as many times the maintainers might not want those changes to be merged or there might be other valid reasons for not adding code to a codebase, especially a large one. Keep submitting code and contributing and you will eventually figure out what kind of PRs are acceptable in each project that you contribue to.

Btw, welcome to our community! 🎆

**Comment by Chalarangelo** [comment]
@saqib053 Archived snippets need the following things:
- A snippet in the `snippets_archive` folder, following the usual guidelines.
- No tags in the `tag_database`.
- (Optional) tests in the `test` folder.

**Pull request closed without merging**
