### PR TITLE
added getStringPermutations

### PR DESCRIPTION
**Pull request by rubiin**
Added getStringPermutations which prints out all the available permutations of a string

### CODE REVIEW

**Review by Chalarangelo — COMMENTED** [review]
Thanks for contributing. However, your PR doesn't follow our [contribution guidelines](../blob/master/CONTRIBUTING.md) correctly and/or it doesn't provide enough value for the average reader. Closing due to that.

**Comment by rubiin** [comment]
@Chalarangelo I have followed the guidelines, what is the specific issue

**Comment by dhruvgaloriya** [comment]
@rubiin same issue with me

**Comment by rubiin** [comment]
> @rubiin same issue with me

yes if the specific issue is not specified, then how will it be fixed.

**Pull request closed without merging**
