### PR TITLE
Adding snippet to generate random alphanumeric strings.

### PR DESCRIPTION
**Pull request by brenohq**
Adding snippet that generates a random alphanumeric string based on `Math.random.toString(radix)` with `radix = 36`.

### CODE REVIEW

**Review by Chalarangelo — COMMENTED** [review]
Thanks for the contribution. However, the snippet is not following guidelines correctly (title doesn't match file name, code is not highlighted in description, indentation is incorrect) and is also not an elegant approach and one with varying complexity for the same input. Closing due to that.

**Comment by brenohq** [comment]
@Chalarangelo what u mean with "an elegant approach and one with varying complexity for the same input"?

**Comment by brenohq** [comment]
> Thanks for the contribution. However, the snippet is not following guidelines correctly (title doesn't match file name, code is not highlighted in description, indentation is incorrect) and is also not an elegant approach and one with varying complexity for the same input. Closing due to that.

Can you help me resolve these points before I open another pull request? Thanks.

**Comment by brenohq** [comment]
Hi @Chalarangelo!

Can you help me to understand why this PR it was tagged as invalid?

I didn't find info about when one PR is marked as invalid.

**Pull request closed without merging**
