### PR TITLE
swift version

### PR DESCRIPTION
**Pull request by elizabethsiegle**
## Description

Added link to the Swift version I made

n/a

n/a

## PR Type
- [ ] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [* ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [ *] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
- [* ] My PR doesn't include any `testlog` changes.

### CODE REVIEW

**Comment by skatcat31** [comment]
@elizabethsiegle just for clarification about your repository, it's going to be `swift` language snippets and the fork was a starting point for the generation scripts?

**Comment by elizabethsiegle** [comment]
yes, that is right @skatcat31!

**Comment by atomiks** [comment]
Just wondering why you'd make this PR now if you haven't actually started creating Swift versions of the snippets yet? I mean the fork only has 1 commit ahead of master and is the exact same right now

**Comment by elizabethsiegle** [comment]
OH I'm sorry, I misunderstood the snippets part--I meant snippets in the repo I linked to in the README. Will get to those later today.

**Comment by skatcat31** [comment]
I think there is still some confusion on our parts about the purpose of the MR and your fork ATM. That can be cleared up at some other point in time. Probably in an issue suggesting a new child repo.

Until then I will be closing this MR as you should not be submitting changes to auto generated files but to the generation parts.

We thank you for wanting to contribute, and if there is anything we can help with or help clarify do let us know.

**Pull request closed without merging**
