### PR TITLE
[FEATURE] Adding Heron's formula for area of any triangle

### PR DESCRIPTION
**Pull request by kylebegovich**
Heron's Formula for Area of any (valid) triangle.

## Description
Adding heronArea.js and adding the corresponding entry in tag_database. More info on Heron's formula (and why it works) here: https://en.wikipedia.org/wiki/Heron%27s_formula. This is exceptionally helpful for simplifying any math being done inside your JS, and abstracts away any altitude calculations being done before the (1/2)bh calculation often used instead.

## PR Type
- [x] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by fejes713** [comment]
Thanks for contributing 👍 I see this snippet as a good example for absolute beginners but other than that I see no real-world use case for this. 

@skatcat31 @Chalarangelo could you give your opinion on this one? I am not against merging it, I just do not see real value in here - I might be wrong though.

**Comment by Chalarangelo** [comment]
My opinion is that it probably belongs in the archive, but I'll have to investigate a bit before concluding.

**Comment by fejes713** [comment]
Having snippets like these might not be the best fit for the current website but as you said they should belong to the archive. By adding them there, we can definitely use it later down the road. 

I vote +1 for adding this to the archive. 👍

**Comment by fejes713** [comment]
Hey, @kylebegovich could you move your snippet to `snippets_archive` before I merge this? Thanks

**Comment by kylebegovich** [comment]
Moved the code snippet and removed the line from the tag_database. Lmk if there's anything else for me to do!

**Pull request merged**
