### PR TITLE
fix(snippet): Simplify formToObject using new methods.

### LINKED ISSUE #990: Simplify formToObject
## Description

[formToObject](https://github.com/30-seconds/30-seconds-of-code/blob/master/snippets/formToObject.md) could be simplified to use of two new methods:

[FormData.prototype.entries()](https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries#Browser_compatibility)
[Object.fromEntries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries#Browser_compatibility)

They are supported in Chrome 73+, Firefox 63+ and Safari 12.1+

### Previous version:
```js
const formToObject = form =>
  Array.from(new FormData(form)).reduce(
    (acc, [key, value]) => ({
      ...acc,
      [key]: value
    }),
    {}
  );
```

### Updated version:

```js
const formToObject = form => Object.fromEntries(new FormData(form).entries())
```

### PR DESCRIPTION
**Pull request by Greenheart**
# FIX: Simplify formToObject by using new methods

## Description

As stated in the issue discussion in #990, we should wait some time before merging this to allow the new method `Object.fromEntries()` to get standardized. But once the standard is stable, this is ready to be merged.

`Object.fromEntries()` is currently a `Draft`, implemented in Chrome 73+, Firefox 63+ and Safari 12.1+.

This change would make `formToObject()` much easier to read.

Tests passing.

Resolves #990

## PR Type
- [x] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by skatcat31** [comment]
I could have sworn our test files were auto generated from the markdown file. Either way a great submission, and will be merged as soon as Object.fromEntries is no longer in draft status

**Comment by Greenheart** [comment]
@skatcat31 Thanks! You're correct, the test files are generated on `npm test`. I guess we could remove the changes to `_30.js`, though it's been committed earlier.

**Comment by skatcat31** [comment]
It will just be replaced with the auto generated file, and since the contents would(ostensibly) be the same, not cause a change

**Comment by skatcat31** [comment]
Otherwise you can so reset to the previous commit, and then only commit the changes you want to your branch and push again

**Comment by lucas500** [comment]
Very good boy

**Comment by Chalarangelo** [comment]
Closing as #990 is frozen indefinitely.

**Pull request closed without merging**
