### PR TITLE
 [ENHANCEMENT] Simpler solution to mask using padStart

### PR DESCRIPTION
**Pull request by Theomg**
## Description
As asked in https://github.com/30-seconds/30-seconds-of-interviews/pull/107#issuecomment-424019789, I'm making a pull request to the same changes merged in 30 seconds of interviews.

Using `String.padStart` we can make the `mask.md` snippet a bit simpler.

## What does your PR belong to?
- [ ] Website
- [x] Snippets
- [ ] General / Things regarding the repository (like CI Integration)
- [x] Tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking improvement of a snippet)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the changes are working properly
- [x] I have checked that there isn't any PR doing the same
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
This is a comment on the snippet itself. String slice is a pure function. Why are we copying it?

**Comment by skatcat31** [comment]
`'' + cc` is used twice in the snippet. We could just use `cc.slice()`

**Comment by Chalarangelo** [comment]
`'' + cc` is used to cast to a string if the value provided is not a string, I think. Am I mistaken?

**Comment by skatcat31** [comment]
Fair point, but there has to be a better more readable way to cast it once and use it once

**Comment by Chalarangelo** [comment]
`${cc}` maybe?

**Comment by Theomg** [comment]
@skatcat31 

I did think it was a bit weird that cast was done twice but decided to leave it alone.
Would you prefer if I cast it once in a const and reused such as:
```js
const mask = (cc, num = 4, mask = '*') => {
  const str = c.toString();
  return str.slice(-num).padStart(str.length, mask);
}
```

**Comment by Chalarangelo** [comment]
@Theomg while this has a small performance increase, it makes the snippet longer and arguably uglier. I prefer just casting twice via template but that's my personal opinion. What do you guys think? @atomiks @fejes713 @flxwu @skatcat31

**Comment by flxwu** [comment]
I'd prefer the ``${cc}``, if that works properly.

**Pull request merged**
