### PR TITLE
adds newCSSRule()

### PR DESCRIPTION
**Pull request by KovaCro**

### CODE REVIEW

**Review by vitogd — APPROVED** [review]

**Comment by fejes713** [comment]
Hey, @KovaCro 👋 thanks for this pull request! 

Could you please follow up in this discussion with some real-life use cases for this snippet such as places where it would be relevant? 

☝️ we are trying to include only content with a solid use-case base right now so are carefully evaluating every submission

**Comment by KovaCro** [comment]
If you want to dynamically change pseudo-class (like :active or :hover) , you can't do that directly through javascript because inline attributes (style="") can't change pseudo-classes. This snippet helps inject a new <style> element. There are several more examples with CSS At-rules, CSS variables and other.

**Comment by KovaCro** [comment]
I accidentally pushed another commit to the master.
Let me know if it's fine or I should revert.

**Comment by Chalarangelo** [comment]
@KovaCro The use case sounds valid. Can you please rebase your branch, drop the extra commit and force push it, so it only contains the original file?

**Comment by KovaCro** [comment]
Sorry for this. lol

I reverted it.

**Comment by KovaCro** [comment]
Still want me to rebase or revert was enough?

**Comment by Chalarangelo** [comment]
@KovaCro Please rebase and only pick the commit that adds the snippet if possible.

**Comment by KovaCro** [comment]
Done.

**Review by Chalarangelo — APPROVED** [review]
The snippet seems interesting, but the implementation is lacking. I'll make some changes to it and merge it. Please follow guidelines more carefully if you wish to contribute any more snippets.

**Pull request merged**
