### PR TITLE
new snippet length of last word

### PR DESCRIPTION
**Pull request by Kennedy-Njeri**
how to get the length of the last word

### CODE REVIEW

**Comment by opticalpalace080** [comment]
How to take stuck money to my account

**Review by opticalpalace080 — APPROVED** [review]

**Comment by Juandieruiz** [comment]
something like that happened to me, be careful you can lose it, as in my
case

**Comment by opticalpalace080** [comment]
How to take cash in my account please share me a link to take out my cash

**Review by Chalarangelo — COMMENTED** [review]
Thank you for contributing but this snippet does not follow guidelines and doesn't add any value for our users.

**Pull request closed without merging**
