### PR TITLE
Update glossary terms

### PR DESCRIPTION
**Pull request by tricinel**
I've added glossary descriptions for Web Components and Shadow DOM. :)
## PR Type
- [ ] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [x] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by skatcat31** [comment]
I can't even remember the last time I've heard of people mentioning web components due to complexity and dom explosion... I think it's been close to a year since the webcomponents.org website was last touched with news too... This is still useful information, but I'm curious how much we should put it in without disclaimers. Thoughts?

**Comment by tricinel** [comment]
Hey! Thanks for reviewing :)

I've recently listened to a podcast about Web Components and they (re)sparked my interest. I think they're still viable (especially with polyfills for sure). I wasn't sure where to put disclaimers, the proper way to do include them in the md file I mean.

Adding scripts is **very** nicely documented, but for the glossary, I had to read previously accepted PRs to get a feel for what's what. Any guidance is appreciated 👍

**Comment by tricinel** [comment]
👍 Completely agree! I would say (hope) they're not abandoned, although they certainly don't get the "visibility" and thumbs up that React/Vue/Angular/Ember get.

Let me know how I can help!

I'd avoid putting a disclaimer, if only just because it _might_ create a precedent. You then have to add disclaimers to es2018 features like object spread and such 👎

**Comment by skatcat31** [comment]
yes... I too am on the fence about disclaimers except for extremely dangerous or possibly depricated code

**Comment by tricinel** [comment]
Thank you for taking a loo @Chalarangelo! Sounds good to me! I'll look to adding a few more during the weekend.

Cheers,
Bogdan

**Pull request merged**
