### PR TITLE
[FEATURE] added midpoint.md & midpoint.test.js

### PR DESCRIPTION
**Pull request by Swhite9478**
## Description

Created midpoint.md to demonstrate how to calculate the midpoint between two pairs of (x,y) points, as well as unit tests to prove validity. I had an issue while running `npm run tester` with  **tomorrow.js** despite this not being my contribution. I am running this in an ubuntu 16.0 virtual box. This was error that was raised:

```
#  FAIL  test/tomorrow.test.js

ok 1 — tomorrow is a Function
ok 2 — Returns the correct year
ok 3 — Returns the correct month
not ok 4 ● Returns the correct date
#   
#   expect(received).toBe(expected) // Object.is equality
#   
#   
#   Expected: 8
#   
#   Received:
#   
#   Stack:
#   
#       at Object.toBe (test/tomorrow.test.js:16:24)
#   
#             12 | test('Returns the correct month', () => {
#             13 |   expect(t1.getMonth()).toBe(t2.getMonth());
#             14 | });
#             15 | test('Returns the correct date', () => {
#           > 16 |   expect(t1.getDate()).toBe(t2.getDate());
#                |                        ^
#             17 | });
#             18 | 
#   
#           at new Promise (<anonymous>)
#           at <anonymous>
```

## PR Type
- [x] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
- [ ] My PR doesn't include any `testlog` changes.

### CODE REVIEW

**Comment by Swhite9478** [comment]
>           Please only submit changes to the snippet file, test file for the snippet, and the tag database. Everything else is generated and should not be pushed. You can easily do these in line by reverting the changes to those files you were not supposed to commit on the commit you changed them. If you do not know how to do that, than please close this pull request and resubmit with only the new files.


Thank you for the quick feedback! I have a question regarding the testing process: You say to only submit the updated tag database, the snippet.md, and the snippet.test.js. In my testing I made changes to the _30s.js file to allow my tests to go through the pipeline, but I am not supposed to do this? Thank you for your help, considering I'm new here!

**Comment by Swhite9478** [comment]
The unnecessary changes have been reverted! Thanks for the advice, and I'm looking forward to making more contributions!

**Comment by Chalarangelo** [comment]
I am going to close this as it alters a lot of files and mucks up the git history. Please feel free to open a new PR with your changes, following the contribution guidelines. Thank you!

**Comment by Swhite9478** [comment]
Sorry about that! I think I understand how to properly contribute now!

**Pull request closed without merging**
