### PR TITLE
Create numToCurrency.md in snippets folder

### PR DESCRIPTION
**Pull request by syamilAbdillah**

### CODE REVIEW

**Comment by davoodgf** [comment]
If you send a message, send it in Fatrasi language

**Comment by davoodgf** [comment]
If you send a message, send it in Fatrasi language

**Comment by davoodgf** [comment]
If you send a message, send it in Persian

**Comment by davoodgf** [comment]
If you send a message, send it in Persian

**Comment by davoodgf** [comment]
If you send a message, send it in Persian

**Review by Chalarangelo — COMMENTED** [review]
Thanks for contributing. However, this is a duplicate of [`toCurrency`](https://www.30secondsofcode.org/js/s/to-currency).

**Comment by davoodgf** [comment]
With all the facilities you have, you can not send your message in Persian and you are oriented towards my mother tongue. With this action, I will not reply to messages or programs or any text sent other than in Persian, and  You send a message again asking for a confirmation or confirmation or exit.  داود غفارزاده یکشنبه, ۰۴ اکتبر ۲۰۲۰, ۱۰:۴۲ق.ظ +03:30 from Angelos Chalaris  notifications@github.com :

**Comment by syamilAbdillah** [comment]
oh i dont know it had been exist. i'll make other snippets

thank you 👍

**Pull request closed without merging**
