### PR TITLE
Feature/get difference in seconds

### PR DESCRIPTION
**Pull request by sujit510**

### CODE REVIEW

**Comment by DrSameerHealth** [comment]
👍

**Review by MJjames43 — COMMENTED** [review]
snippets/getDifferenceInSeconds.md

**Review by yashasbyte — APPROVED** [review]

**Review by seasar624 — APPROVED** [review]

**Review by sowmenappd — COMMENTED** [review]
Function is alright, but maybe providing a bit more information about how the algorithm works is needed.

**Review by Trinityyi — APPROVED** [review]
Thanks for the contribution. I did some minor changes and I will merge this.

**Pull request merged**
