### PR TITLE
Add slugify

### PR DESCRIPTION
**Pull request by vincentdoerig**
I also changed a `let` to a `const` in `yesterday.md` as per the [Snippet guidelines](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md%23snippet-guidelines).

### CODE REVIEW

**Comment by davoodgf** [comment]
With all the facilities you have, you can not send your message in Persian and you are oriented towards my mother tongue. With this action, I will not reply to messages or programs or any text sent other than in Persian.  داود غفارزاده یکشنبه, ۰۴ اکتبر ۲۰۲۰, ۱۰:۲۰ق.ظ +03:30 from Vincent Dörig  notifications@github.com :

**Comment by davoodgf** [comment]
With all the facilities you have, you can not send your message in Persian and you are oriented towards my mother tongue. With this action, I will not reply to messages or programs or any text sent other than in Persian.  داود غفارزاده

**Comment by davoodgf** [comment]
With all the facilities you have, you can not send your message in Persian and you are oriented towards my mother tongue. With this action, I will not reply to messages or programs or any text sent other than in Persian.  داود غفارزاده یکشنبه, ۰۴ اکتبر ۲۰۲۰, ۱۰:۲۸ق.ظ +03:30 from تاکسی هجرت  hejrattaxi@yahoo.com :

**Review by Chalarangelo — APPROVED** [review]
Thanks for contributing. Please remember to submit only one change per snippets. The `const` to `let` change was mostly valid, but `let` is used there to indicate that the value will be mutated later in the code (next line). The `slugify` snippet seems solid, so I'll make a few minor changes and merge it. Cheers.

**Pull request merged**
