### PR TITLE
feat: add compactObject snippet

### PR DESCRIPTION
**Pull request by anhzf**
accept for hacktoberfest please... thank you
btw this is my first to contribute... ✌
any advice is accepted

### CODE REVIEW

**Review by 53jk1 — CHANGES_REQUESTED** [review]
There is a bug in the code, `compact` is not defined.

**Comment by anhzf** [comment]
> There is a bug in the code, `compact` is not defined.

I'm sorry im trying to change the function name, i forgot about it. Thank you

**Review by Chalarangelo — COMMENTED** [review]
Seems interesting, I'll make some changes and merge this.

**Comment by anhzf** [comment]
> Seems interesting, I'll make some changes and merge this.

haha, sorry for my bad english

**Pull request merged**
