### PR TITLE
Add squareSum

### PR DESCRIPTION
**Pull request by saqib053**
## PR Type
- [x] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
- [x] My PR doesn't include any `testlog` changes.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I made a couple of improvements. My only question is as follows:

- Should this maybe be changed to a variadic footprint to be easier to use for a broader range of cases?

**Comment by saqib053** [comment]
What do you mean by variadic footprint? If there is something to improve upon then why not.

**Comment by Chalarangelo** [comment]
I mean that, instead of an array, this could take one `...args` argument, which could be used with arrays or single values (like `squareSum(...arr)` or `squareSum(1,2,3)`). We usually do this in similar snippets to accommodate more use-cases.

**Comment by saqib053** [comment]
yeah, it could be changed.

**Pull request merged**
