### PR TITLE
added stringRotation.md

### PR DESCRIPTION
**Pull request by PeadarODonnell**

### CODE REVIEW

**Comment by fejes713** [comment]
Hey, @PeadarODonnell 👋 Thanks for opening this PR. 

It does look interesting but what would be the use case of this snippet? 

At this stage, we are trying to add quality content to 30-seconds with real-life use cases. This one doesn't seem that useful to me 😕 Could you provide some real-life use cases? Thanks!

**Comment by Chalarangelo** [comment]
Thanks for contributing, but I'm also pretty certain this has no real-life applications for the most part. Closing due to that.

**Comment by PeadarODonnell** [comment]
That's fair enough, it had a really specific use case, ie. if you were looking for a string rotation between two strings of same length but yeah, you's are right when I look at it, not a lot of people will actually be searching for a string rotation in real life :disappointed_relieved: 
But thank you so much for looking at it and giving advice, I definitely want to add only quality content to 30-seconds in the future! :smile:

**Comment by Bryan-Herrera-DEV** [comment]
:3

**Pull request closed without merging**
