### PR TITLE
Update createDirIfNotExists function

### PR DESCRIPTION
**Pull request by you-think-you-are-special**
## Description
Modified `createDirIfNotExists` snippet. Now it is asynchronous and safe. Those reasons are attached in the snippet description:

```
Using fs.exists() to check for the existence of a directory before calling fs.mkdir() is not recommended. 
Doing so introduces a race condition, since other processes may change the directory's state between the two calls. 
Instead, user code should create the directory directly and handle the error raised if the directory does not exist.

Why not fs.mkdirSync? In busy processes, the programmer is strongly encouraged to use the asynchronous versions of these calls. 
The synchronous versions will block the entire process until they complete — halting all connections.
```

Also, updated `module.js` script. It didn't want to work with multiple `require`

## PR Type
- [x] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [x] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by you-think-you-are-special** [comment]
It will break the tests. Are you sure?

**Comment by Chalarangelo** [comment]
Why would a snippet change require a change in a script to work?

**Comment by you-think-you-are-special** [comment]
I use two `require` in snippet.
```js
const fs = require('fs');
const util = require('util');
```
Unfortunately, script can't handle this. The script loses second one. Am I wrong?

**Comment by Chalarangelo** [comment]
You should be using something along the lines of 
```js
const fs = require('fs'), util = require('util');
```

**Comment by you-think-you-are-special** [comment]
I've already tried this. It generates that code and won't work

```
const fs = typeof require !== "undefined" && require('fs');
const crypto = typeof require !== "undefined" && require('crypto');
const fs = typeof require !== "undefined" && require('fs'), util = require('util');
```

**Comment by Chalarangelo** [comment]
I am tagging as `on hold` until I can get back to you about the `require` issue, hopefully later today or tomorrow.

**Comment by you-think-you-are-special** [comment]
Why my pull request was closed?

**Pull request closed without merging**
