### PR TITLE
Device Information

### PR DESCRIPTION
**Pull request by TheCoderAS**
javascript snippet for getting device hardware information and browser information

### CODE REVIEW

**Comment by alabazidi** [comment]
unsubcribe me

**Comment by TheCoderAS** [comment]
What happened??

**Review by Trinityyi — COMMENTED** [review]
Thanks for contributing. However, your PR doesn't follow our [contribution guidelines](../blob/master/CONTRIBUTING.md) correctly and it doesn't provide any value for the average reader. Closing due to that.

**Comment by TheCoderAS** [comment]
May you please explain to me, how can my PR fulfill contribution
guidelines? I've read all the guidelines carefully and contributed
accordingly.
Kindly clarify and help me understand.
Thanks and regards.

**Pull request closed without merging**
