### PR TITLE
Update toCamelCase snippet to use const instead of let

### PR DESCRIPTION
**Pull request by lukasbals**
Update `toCamelCase` snippet to use `const` instead of `let`.

### CODE REVIEW

**Review by Chalarangelo — APPROVED** [review]

**Comment by JoeLeeCS** [comment]
👍

**Comment by 274dolphin** [comment]
👍

**Comment by asemanali** [comment]
hello, do any of friends have the code for forward calculation for a magnetic field of a dyke which is under ground? thanks..

**Comment by asemanali** [comment]
it is related to geophysics (geomagnetism)

**Review by antonioac7 — COMMENTED** [review]
Remove all info in my account please

**Pull request merged**
