### PR TITLE
dropProperties snippet for array of objects

### PR DESCRIPTION
**Pull request by antekai**
## Description
Adds new snippet (.md, tests, tag_database) that drops properties in an array of objects (i.e. response data). Note that I added manually test files and run them in a different (isolated) environment as the `tester` and `test` script of this repo throws me an error and exits (not yet resolved).

## PR Type
- [x] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [ ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
- [x] My PR doesn't include any `testlog` changes.

### CODE REVIEW

**Comment by Chalarangelo** [comment]
This is pretty much the same as [omit](https://30secondsofcode.org/object#omit). Closing on that basis...

**Comment by skatcat31** [comment]
If you wanted to use this type of logic with omit, you would map over the array with a curried omit

```js
const omit = (obj, arr) =>
  Object.keys(obj)
    .filter(k => !arr.includes(k))
    .reduce((acc, key) => ((acc[key] = obj[key]), acc), {});

var test = [{ id: 1, test: 1, t2: 1 },{ id: 2, test: 2, t2: 3 }]

var removeKeys = (...keys) => obj =>omit(obj, keys)

test.map(removeKeys('test', 't2')) // [{ id: 1}, { id: 2 }]
```

**Comment by antekai** [comment]
Thank you for the fast review of my PR and for the example of `omit()` extended for an objectArray. I thought it might be more simple to understand and possibly more efficient to build snippets targeted to objectArrays than trying to fit array or object snippets to objectArrays (response data). This was mostly a sample about a possible new category of snippets.

PS. 1. Bravo for the work on 30-seconds-of-code, really unique and useful resource :1st_place_medal: 
2. a screenshot to preview readability and performance. Bonus a 3rd (i believe the best) way to do this.
screenshot_2

**Comment by skatcat31** [comment]
To be fair `omit` has a timing complexity problem that makes it fairly slow(comparatively, otherwise it's still plenty fast enough for real world use in most cases)

I wonder the performance difference between the following:

```js
const omit = (obj, arr) =>
  Object.keys(obj)
    .reduce((acc, key) => ((!arr.includes(k) ? (acc[key] = obj[key]) : null), acc), {});
```

This one is however MUCH harder to read

**Pull request closed without merging**
