### PR TITLE
[ENHANCEMENT] Improve user experience by making possible to click the entire box (menu item), not only the text.

### PR DESCRIPTION
**Pull request by maikenegreiros**
## Description
In the menu bar, the items is not entirely clickable, the click only works in the words. In very small words like "all" or "any" the problem is more notable. So I turned the whole item clickable to improve the user experience.

## PR Type
- [ ] Snippets, Tests & Tags (new snippets, updated snippets, re-tagging of snippets, added/updated tests)
- [ ] Scripts & Website & Meta (anything related to files in the [scripts folder](https://github.com/30-seconds/30-seconds-of-code/tree/master/scripts), how the repository's automated procedures work and the website)
- [ ] Glossary & Secondary Features (anything related to the glossary, such as new or updated terms or other secondary features)
- [x] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)

## Guidelines
- [x] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
- [x] My PR doesn't include any `testlog` changes.

### CODE REVIEW

**Comment by fejes713** [comment]
Hey, @maikenegreiros thanks a ton for implementing this! This UX problem was hunting us for a longer time now. I noticed it as well 👍 

I currently do not have a laptop with me so I am not able to test this right now. Until then if someone tests this and works as expected feel free to merge!

**Comment by skatcat31** [comment]
Why wouldn't we just hoist the link to surround the parent element of the text/menu item?

**Comment by maikenegreiros** [comment]
Are you suggesting the link to be li's parent node? I think it's not a good idea. It's not semantic. The HTML structure is fine, I think the best way is work in the css.

**Comment by skatcat31** [comment]
fair... the only thing that's supposed to be in <ul> is <li>...

If that's the case shouldn't we instead implement a CSS rule?

```css
li a {
     display: block;
     width: 100%;
     height: 100%;
}
```

**Comment by anaiy** [comment]
Cancel my subscription

در چهارشنبه ۷ نوامبر ۲۰۱۸،‏ ۵:۱۱ Maike Negreiros <notifications@github.com
نوشت:

**Pull request merged**
